apiVersion: v1
kind: Service
metadata:
  name: hero-service
spec:
  selector:
    app: hero-pod
  ports:
  - port: 5055
    nodePort: 30055
    protocol: TCP
    targetPort: 5056
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hero-pod
  template:
    metadata:
      labels:
        app: hero-pod
    spec:
      containers:
      - name: hero-container
        image: pichayean/blazorhero:v1.0.1
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: Production
        ports:
        - containerPort: 5056
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: shorturl-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: hero.codingholiday.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: hero-service
           port:
             number: 5056
